title: "Janghyun Noh"
url: "https://Janghyun.github.io"
name: "Janghyun Noh"
position: "M.S. student at Myongji University"
location: "Seoul, Korea"
affiliation: "AIDA, Myongji University"
email: "watercar99@naver.com"
google_scholar: "https://scholar.google.com/citations?user=NPIG8VoAAAAJ&hl=ko&oi=ao" 
github: "https://github.com/janghyunnoh"
# linkedin: "https://www.linkedin.com/in/your-id/"
